In [2]:
import pandas as pd

In [3]:
data_ise = pd.read_excel('./data.xlsx', sheet_name='indicadores_socioeconomicos')
data_ise.head()

,Ano,Governo,Partido,PIB (US$),PIB Per Capita (US$),Desemprego (%),Inflação (%),Homícidos (/100k),IDH,IDH (posicao),Índice de Gini
0,1991,NaN,NaN,342609227209.645447,2259.239894,0.06314,4.327867,18.561716,0.621,84,NaN
1,1992,NaN,NaN,328187944300.907776,2127.50719,0.0642,9.519621,16.833232,0.627,84,53.2
2,1993,NaN,NaN,368295777770.079468,2348.090047,0.0603,19.273808,17.859684,0.635,84,60.1
3,1994,NaN,NaN,525369851353.742188,3295.244924,0.06169,20.758884,18.723517,0.642,84,NaN
4,1995,FHC,PSDB,769333330368.986816,4748.388208,0.0642,0.66007,20.985134,0.651,82,59.6

In [4]:
data_ise = pd.read_excel('./data.xlsx', sheet_name='indicadores_socioeconomicos')
data_gastos = pd.read_excel('./data.xlsx', sheet_name='gastos_união_por_setor')
data_gastos.head()

,Ano,Governo,Partido,Legislativa,Judiciária,Essencial à Justiça,Administração,Defesa Nacional,Segurança Pública,Relações Exteriores,...,Ciência e Tecnologia_perc,Agricultura_perc,Organização Agrária_perc,Indústria_perc,Comércio e Serviços_perc,Comunicações_perc,Energia_perc,Transporte_perc,Desporto e Lazer_perc,Encargos Especiais1_perc
0,2000,FHC,PSDB,1757003918,6478450642,679352430,6587307707,10634132067,2188593405,748364647,...,0.003947,0.016113,0.003466,0.001023,0.005908,0.001279,0.001661,0.010428,0.000551,0.423644
1,2001,FHC,PSDB,2109472834,6715564221,859504600,7265908231,11891512769,2604286208,925811930,...,0.004152,0.014298,0.003469,0.001244,0.007257,0.00119,0.001895,0.010334,0.000777,0.455188
2,2002,FHC,PSDB,2474354441,8186935072,1043701170,8228736910,12616520363,2202448059,1328092746,...,0.003431,0.012527,0.003144,0.000951,0.004169,0.00129,0.017808,0.011711,0.000603,0.453419
3,2003,Lula,PT,3075018192,8359812944,1356059636,7362507102,11570137295,2405123126,1164074395,...,0.00404,0.013186,0.002897,0.00089,0.004189,0.0013,0.007916,0.006178,0.000324,0.468213
4,2004,Lula,PT,3535512778,10530935648,2126077659,8936536575,13573310106,2767855746,1311767179,...,0.004795,0.014043,0.004814,0.002848,0.003833,0.000913,0.000728,0.006715,0.000499,0.438166

In [12]:
data_ise.iloc[:-2]['Índice de Gini'].astype(float).round()

0      NaN
1     53.0
2     60.0
3      NaN
4     60.0
5     60.0
6     60.0
7     60.0
8     59.0
9      NaN
10    58.0
11    58.0
12    58.0
13    56.0
14    56.0
15    56.0
16    55.0
17    54.0
18    54.0
19     NaN
20    53.0
21    53.0
22    53.0
23    52.0
24    52.0
25    53.0
26    53.0
27    54.0
28    54.0
29    49.0
30     NaN
Name: Índice de Gini, dtype: float64